Atualizando entrada
lucasljf/erp pull request #47
Opened 2024-03-21 01:37 UTC by xTHs

Retirando os métodos não necessários

2024-03-21 20:02 UTC, lucasljf commented on erp-java/src/main/java/modelo/Entrada.java
> +import java.util.ArrayList;
Esse import é necessário?

2024-03-21 21:45 UTC, xTHs commented on erp-java/src/main/java/modelo/Entrada.java
> +import java.util.ArrayList;
Não é, eu coloquei porquê pensei que fosse implementar os métodos de persistência no BD e depois esqueci ele aí

2024-03-21 22:19 UTC, lucasljf requested changes
Remover o import desnecessário.

2024-03-21 22:22 UTC, lucasljf commented
Após remover o import, faça mais commits e push para branch `2-criação-da-classe-entrada`.
Não é necessário criar um novo pull request.

2024-03-21 23:12 UTC, xTHs commented
Ok, não fiz o pull request

2024-03-26 01:25 UTC, lucasljf approved these changes

2024-03-26 01:25 UTC, merged