adicionando EntradaDao, busca produto
lucasljf/erp pull request #50
Opened 2024-03-23 21:12 UTC by GuiAlencar

2024-03-26 02:08 UTC, lucasljf requested changes

2024-03-26 02:08 UTC, lucasljf commented on erp-java/src/main/java/dao/Conexao.java
Esse arquivo não deveria ser enviado.
Responsabilidade de outro contribuidor.

2024-03-26 02:08 UTC, lucasljf commented on erp-java/src/main/java/dao/EntradaDAO.java
> +    public ArrayList<Entrada> buscar(Produto produto){
Importar classe Entrada.

2024-03-26 02:08 UTC, lucasljf commented on erp-java/src/main/java/dao/EntradaDAO.java
> +                Entrada entrada = new Entrada(rs.getInt("id"));
Observe no repositório a classe **Entrada** (que foi submetida com atraso).
O objeto `Entrada` retornado deve estar completo ao invés de conter apenas o `id`.

2024-03-27 02:28 UTC, GuiAlencar commented
professor, acho que o senhor terá que fechar esse pull request, fiz o commit novamente mas não apareceu para eu criar outro pull request no github desktop

2024-03-27 02:38 UTC, lucasljf commented
> professor, acho que o senhor terá que fechar esse pull request, fiz o commit novamente mas não apareceu para eu criar outro pull request no github desktop

Mas não é preciso mesmo criar um novo Pull Request. Basta fazer novos commits e dar push para a branch que está usando.

2024-03-28 19:33 UTC, lucasljf approved these changes

2024-03-28 19:42 UTC, merged