Criação do método buscar(id e status) - ProdutoDAO e criação de um co…
lucasljf/erp pull request #95
Opened 2024-04-02 00:25 UTC by italo-gs

…nstrutor vazio em Serviço

2024-04-10 03:06 UTC, lucasljf requested changes

2024-04-10 03:06 UTC, lucasljf commented on erp-java/src/main/java/dao/ProdutoDAO.java
> +            stmt.setBoolean(2, status);
Se no banco de dados o `status` é um valor TINYINT, essa atribuição funcionará? Setar um boolean para um SQL que espera um TINYINT?

2024-04-10 03:06 UTC, lucasljf commented on erp-java/src/main/java/modelo/Servico.java
> +    public Servico(){}
Descarte todas as suas alterações do arquivo `Servico.java`.

2024-04-10 03:06 UTC, lucasljf commented on erp-java/src/main/java/dao/ProdutoDAO.java
> +                    Mercadoria produto = new Mercadoria();
Utilize construtores completos.

2024-04-10 03:06 UTC, lucasljf commented on erp-java/src/main/java/dao/ProdutoDAO.java
> +                    Servico produto = new Servico();
Utilize construtores completos.

2024-04-10 23:16 UTC, italo-gs commented
vou fazer as alterações agora

2024-07-03 02:03 UTC, lucasljf approved these changes
Aprovado, contudo, ainda possui falhas que serão corrigidas por novas issues.

2024-07-03 02:10 UTC, merged