teste entradaDao busca(Produto)
lucasljf/erp pull request #98
Opened 2024-04-03 00:40 UTC by GuiAlencar

2024-04-07 17:10 UTC, GuiAlencar commented
Professor, quando vou instanciar um produto, eu tenho que instanciar de acordo a classe produto ou tabela produto do banco ?

2024-04-10 03:22 UTC, lucasljf requested changes

2024-04-10 03:22 UTC, lucasljf commented on erp-java/src/test/java/dao/EntradaDAOTest.java
> +    private void assertNotNull(ArrayList<Entrada> entradas) {
Remover esse método.

2024-04-10 03:22 UTC, lucasljf commented on erp-java/src/test/java/dao/EntradaDAOTest.java
> +    private void assertEquals(int i, int size) {
Remover esse método.

2024-04-13 17:48 UTC, GuiAlencar commented
removi o que o senhor pediu

2024-07-03 17:38 UTC, lucasljf approved these changes

2024-07-03 17:38 UTC, merged